nette/tester

Tester/Runner/Runner.php, tests/Runner.stop-on-fail.phpt, tests/stop-on-fail/init-fail.phptx, tests/stop-on-fail/pass.phptx, tests/stop-on-fail/runtime-fail.phptx
The `Runner::$interrupted` is reseted to FALSE because it is needed in a `--watch` mode. But once per run() is enough.
I hope I didn't forget for some case, it is difficult to create a test case for this behaviour.
=> Runner: interrupted may be set in test initiation phase

Tester/Framework/Environment.php
In current implementation when Environment::lock is called multiple times only last acquired lock is saved. Previous lock are sometimes randomly garbage collected. This results in race conditions and random test failures.
=> Allow to acquire multiple locks

Tester/Runner/info.php
I feel that `--info` output could be more concentrated...
=> info.php: shorter output

Tester/Framework/Environment.php
Contents of static $locks exists only in one process. The acquiring can be skipped when lock already exists in this process.
=> Environment: acquire lock() only if not exist

Tester/Runner/CliTester.php, Tester/Runner/Output/JUnitPrinter.php, Tester/tester.php, readme.md, tests/RunnerOutput/JUnitPrinter.phpt, tests/RunnerOutput/cases/fail.phptx, tests/RunnerOutput/cases/pass.phptx, tests/RunnerOutput/cases/skip.phptx
- feature
- BC break - no
- documentation - not needed
JUnit format specification: http://help.catchsoftware.com/display/ET/JUnit+Format
For example [CircleCI](https://circleci.com/) supports test reports in this format. It shows reports nicely in the GUI.
=> Added support for generating test report in JUnit XML format

src/Runner/ZendPhpInterpreter.php
=> ZendPhpInterpreter: throws exception on PHP startup errors [WIP]

src/Framework/Assert.php, tests/Framework/Assert.contains.phpt, tests/Framework/Assert.count.phpt, tests/Framework/Assert.equal.phpt, tests/Framework/Assert.false.phpt, tests/Framework/Assert.match.phpt, tests/Framework/Assert.nan.phpt, tests/Framework/Assert.null.phpt, tests/Framework/Assert.same.phpt, tests/Framework/Assert.true.phpt, tests/Framework/Assert.truthy.phpt, tests/Framework/Assert.type.phpt
Sometimes test results can be hard to understand without detail examination of test code.
For example:
```PHP
Assert::true($obj->isA());
Assert::true($obj->isB());
```
You just get something like: 
```
Failed: FALSE should be TRUE
in Tester/Framework/Assert.php(370) 
in Tester/Framework/Assert.php(141) Tester\Assert::fail()
in tests/common/SomeTest.phpt(18) Tester\Assert::true()
```
Only information about what caused tha failure is line number on last line.
Also there are some cases when assertion is executed multiple times (for example asserting something for every item in collection) where we need to know for which item test failed.
Therefore it is usefull to have option to add custom fail messafe to asserts.
```PHP
Assert::true($obj->isA(), "Object is A");
Assert::true($obj->isB(), …
```
=> Optional custom fail messages in asserts

src/Framework/Dumper.php
This is somewhat irritating when using diff, as some tools warn about missing newlines, making the diff harder to read.
```php
Assert::same([], ['foo']);
```
before:
```
$ diff a b
1c1
< array()
\ No newline at end of file
---
> array('foo')
\ No newline at end of file
```
after
```
$ diff a b
1c1
< array()
---
> array('foo')
```
=> Dumper: fix php outputs not ending with newline

src/Framework/TestCase.php, tests/Framework/TestCase.annotationThrows.setUp.tearDown.phpt
Currently, when test method is annotated by `@throws` and test method throws an expected exception, the `runTest()` always [escapes by throwing it](https://github.com/nette/tester/blob/fc6d85565097528168ebd9f106744a22d8155ad1/src/Framework/TestCase.php#L136) (or it can be thrown by `setUp()`) and exception from `tearDown()` is never thrown. It can be AssertException and it is buggy to mute it.
Ref #238
=> TestCase: do not mask setUp() and tearDown() exceptions

src/Framework/TestCase.php, tests/Framework/TestCase.dataProvider.generator.phpt, tests/Framework/TestCase.dataProvider.phpt, tests/Framework/TestCase.invalidProvider.phpt
I've found that if you want to return some more complex structures from a data provider or even do some other logic to it inbetween, generators seem to be a more convenient approach than arrays.
In my case, I need to test data validation of a third-party API, generating a valid request and breaking it in a lot of slightly different ways, and generators just seem to be much more expressive:
```php
public function dataProvider()
{
$request = $this->createValidRequest();
unset($request['title']);
yield [$request, 'Missing parameter title'];
$request = $this->createValidRequest();
unset($request['description']);
yield [$request, 'Missing parameter description'];
// ...
}
```
=> TestCase: data provider supports \Traversable

src/CodeCoverage/Generators/HtmlGenerator.php
Source files that was not loaded when executing tests was not counted to coverage. This produces false results.
I've added estimator of executable lines. What do you think about this prototype? I'm not sure about duplicating code between CloverXMLGenerator and HtmlGenerator. PhpParser can provide quite accurate data for estimate of lines that can be estimated.
=> HtmlGenerator: Not loaded source files was not counted to coverage

src/Framework/Dumper.php, tests/Framework/Dumper.toPhp.phpt, tests/Framework/Dumper.toPhp.recursion.phpt
If `Assert:same()` is used to compare two similiar-looking objects and the assert fails, the Tester generates two outputs which shows no difference at all.
This PR prints object's hash to distinguish the objects.
=> Dumper: object hash

.travis.yml, src/CodeCoverage/Collector.php, src/Framework/Environment.php, src/Runner/CliTester.php, src/Runner/ZendPhpDbgInterpreter.php, src/tester.php, tests/Runner/Job.phpt, tests/Runner/Runner.multiple-fails.phpt, tests/Runner/ZendPhpExecutable.phpt, tests/bootstrap.php
Most of critical phpdbg bugs are fixed since RC4, some bugs are however still present.
https://bugs.php.net/bug.php?id=70532
https://bugs.php.net/bug.php?id=70531
https://bugs.php.net/bug.php?id=70614
=> Support for phpdbg with fast code coverage

appveyor.yml, readme.md, src/Framework/Dumper.php, tests/Framework/Dumper.color.phpt
see #269
what is missing:
- the failing test using inverted return code (we should rely on travis)
- printing *.actual content (I'll solve when needed)
- ~~both CLI & CGI testing~~
colors fix is related to https://github.com/appveyor/ci/issues/373, but I am not sure if it should be merged
=> CI AppVeyor

src/Framework/Environment.php, src/Runner/Job.php, src/Runner/Runner.php, tests/Runner/Runner.environment.phpt
Solves #301. Not sure about:
- thread terminology - maybe introduce naming `queue`, `job queue`? Something better?
- `Job::getEnvironmentVariable()` - seems that Runner should not depend on it
=> Pass "thread" number to test

src/Framework/DomQuery.php, tests/Framework/DomQuery.fromHtml.phpt
- bug fix? yes #337
- new feature? no
- BC break? no
- doc PR:
Fix of DomQuery::fromHtml <script> parsing for multiline scripts. Tests adjusted accordingly.
=> DomQuery: fixed multiline <script> parsing

src/Runner/CliTester.php, src/Runner/Output/ConsolePrinter.php, src/Runner/Output/JUnitPrinter.php, src/Runner/Output/Logger.php, src/Runner/Output/TapPrinter.php, src/Runner/OutputHandler.php, src/Runner/Runner.php, src/Runner/TestHandler.php, tests/Runner/Runner.annotations.phpt, tests/Runner/Runner.edge.phpt, tests/Runner/Runner.misc.phpt, tests/Runner/Runner.multiple-fails.phpt, tests/Runner/Runner.stop-on-fail.phpt, tests/RunnerOutput/OutputHandlers.phpt
- bug fix? no, related to #345
- new feature? yes
- BC break? **YES**
- doc PR: will
This BC break storm can be split on:
---
**OutputHandler receives whole Test instance**
So it can reach all its properties, including stout and stderr.
**Added `OutputHandler::prepare(Test $test)`**
So it can perform some prepare actions. AFAIK it is "needed" by @jiripudil for PhpStorm plugin, right?
<del>**OutputHandler is an abstract class instead of the interface**
OutputHandler is the only one place where someone can hook the Tester. It will help to prevent BC breaks</del>
**Dropped runner's `getResults()` and `getJobCount()`**
With `OutputHandler::prepare()` is easy to count jobs and results by its own. Runner itself does not need this methods.
=> OutputHandler v3

src/Runner/Output/ConsolePrinter.php, src/Runner/TestHandler.php, tests/RunnerOutput/OutputHandlers.expect.console.txt, tests/RunnerOutput/OutputHandlers.expect.consoleWithSkip.txt
- bug fix? no
- new feature? no
- BC break? no
Two things by this PR:
- the `Test::$title` purpose redefined, it is filled by `TEST: ...title...` only if exists, otherwise `null`
- common file path of tests is not printed when test fails or is skipped.
```
/home/milo/app/tests/Folder1/TestOne.phpt
/home/milo/app/tests/Folder2/TestOne.phpt
-- FAILED: Folder1/TestOne.phpt
-- FAILED: Folder2/TestOne.phpt
```
This is similar to Tester 1.x behaviour, where only last 3 parts of file path have been shown.
=> ConsolePrinter shows only ending file path

src/Framework/Environment.php, src/Framework/FileMutator.php, src/bootstrap.php, tests/Framework/FileMutator.phpt, tests/Framework/fixtures/final.class.php, tests/coding-standard.neon
- new feature? yes
- BC break? no
This can be used mocking of final classes/members and also as foundation for #17
=> added FileMutator 

src/Framework/DomQuery.php
- bug fix? yes
- new feature? no
- BC break? no
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture
=> DomQuery: added missing error suppression for <picture>

src/Framework/Assert.php, src/Framework/Dumper.php, src/Framework/Expect.php, src/bootstrap.php, tests/Framework/Assert.equal.expect.phpt, tests/Framework/Assert.equal.phpt, tests/Framework/Assert.same.phpt, tests/Framework/Expect.phpt
- new feature
- BC break? no
This PR attempts to simplify the comparsion of structures that contain some variable data like this:
```php
$actual = ['a' => md5($s), 'b' => new DateTime, 'c' => rand()];
$expected = ???
Assert::equal($expected, $actual);
```
I'd like make assertions that 
- `$actual` is array
- it contains keys `a`, `b`, `c`
- and first value is hexa string: `Assert::type('string')` + `Assert::match('%h%', $value)`
- second value is object DateTime: `Assert::type('DateTime', $value)`
- the third value is integer: `Assert::type('int', $value)`) and >= 0 (`Assert::true($value >= 0)`
This PR allows to describe it using Assert::equal()  + language similar to how `Assert` is used. Only `Assert::` is replaced with `Value::`
```php
$actual = ['a' => md5($s), 'b' => new DateTime, …
```
=> Better Assert::equal() WIP

src/Framework/Helpers.php
- new feature?  
- BC break? no
1) Prevents an incorrect call with an empty parameter (eg due to a typo in the code), which can lead to the whole disc being deleted
2) Disables `purge('/')` or `purge('c:/') just for sure
=> Helper::purge() protection [WIP]

src/Framework/Environment.php
- bug fix
- BC break? yes
In case of Doctrine ORM Schema update when all entities are loaded automatically, `$trace` with index `file` can be undefined.
=> Environment: File can be undefined.

readme.md
- bug fix #409 
- BC break? no
Added documentation how call private method.
=> readme: added with()

src/CodeCoverage/Collector.php, src/Runner/CliTester.php, src/Runner/info.php, tests/CodeCoverage/Collector.phpt, tests/Runner/PhpInterpreter.phpt
- bug fix
- BC break? no
- doc PR: not necessary
[Xdebug 3](https://xdebug.org/docs/upgrade_guide) requires `xdebug.mode` to include `coverage` for coverage to work, otherwise coverage-related symbols are not defined and tests fail with `Error: Undefined constant "Tester\CodeCoverage\XDEBUG_CC_UNUSED"`.
Users can make it work by running tester with `-d xdebug.mode=coverage`, but I thought tester could setup this automatically, so that it works out of the box as with Xdebug 2. Therefore, this PR adds version number to code coverage engine info and uses that to automatically setup `coverage` mode for test processes when Xdebug >= 3.0.0 is used.
=> CodeCoverage: better support for Xdebug 3

src/Framework/Assert.php, tests/Framework/Assert.type.phpt
- bug fix
- BC break? no
- doc PR: not necessary
Apparently `Assert::type()` supports an object instance in place of expected `$type`, but if such assertion fails, building a failure message produces either an `Error: Object of class (...) could not be converted to string`, or a rather misleading message if the expected type implements `__toString`.
=> fix Assert::type() failure error when expected $type is object

src/Framework/Assert.php, tests/Framework/Assert.hasKey.phpt
- new feature
- BC break? no
- doc PR: nette/docs#???  On its way
Add simple assertions hasKey nad hasNotKey to tester. They are very useful for testing restful api responses.
Tests included.
=> Add hasKey and hasNotKey assertions

src/Runner/CliTester.php, src/Runner/CommandLine.php, src/Runner/Output/ConsolePrinter.php, src/Runner/Output/JUnitPrinter.php, src/Runner/Output/Logger.php, src/Runner/Output/TapPrinter.php, tests/Runner/CommandLine.phpt
=> The -o option can be used multiple times No.2

src/Framework/TestCase.php, src/Runner/Runner.php, src/Runner/TestHandler.php, tests/Runner/Runner.multiple-fails.phpt
- bug fix? no
- new feature? yes
- BC break? no
- doc PR: no needed
This PR tries to solve #369 as follows.
Output of test method listing is now in format:
```
$ php tests/Framework/Assert.equal.recursive.phpt --method=nette-tester-list-methods
TestCase:RecursionTest
Method:testSimple
Method:testMultiple
Method:testDeep
Method:testCross
Method:testThirdParty
Dependency:D:\Web\dev\nette\tester\tests\Framework\Assert.equal.recursive.phpt
Dependency:D:\Web\dev\nette\tester\src\Framework\TestCase.php
```
The `TestCase:...` line is here only for check, that `TestCase::run()` method is run.
The `Method:...` lines are test methods, formerly as `[testSimple,testMultiple,...]`.
The `Dependency:...` lines are new. It is a list of declaring files. TestCase class, all its parents and all traits. With …
=> TestCase methods listing caching

src/Runner/CliTester.php
- bug fix
- BC break? no
Added new line at the end to avoid this:
Generating code coverage report... failed. Coverage file is empty. Do you call Tester\Environment::setup() in tests?diego@localhost $
=> CliTester: added missing newline

src/Runner/TestHandler.php, tests/Runner/Runner.multiple-fails.phpt, tests/Runner/multiple-fails/dataprovider-empty.phptx
Related to 1f4bce20a4142f5b1285d1eb9ae546ed5ef27e06
=> TestHandler: mark tests with empty data provider as failed/skipped

src/Framework/Environment.php
- bug fix
- BC break? no
This is alternative for fixing issue described in #441. 
Why am I doing a second PR? Because I think that hitting `src/Framework/TestCase.php` is not good. That's why I'm defining the property to the default value in the PR.
Why did the code work before? PHP dynamically initialized the property to null. But after adding a type, it starts to fail. Via sample https://3v4l.org/dmghh Commit hash that clogged this problem [e445e74b](https://github.com/nette/tester/commit/e445e74b8a16bbdfa8222b46edd5d377dd435cd8#diff-739a29dbff2caac04e06818e0ac275ee2983c85b8f75624ce3c08c96835d95c0R34). 
Sample error on URL https://github.com/php-parallel-lint/PHP-Parallel-Lint/actions/runs/4834553343/jobs/8615917976
=> fixed accessed property before initialization

phpstan.neon, readme.md, src/Runner/CliTester.php, src/Runner/Output/ConsolePrinter.php, src/Runner/Test.php, tests/RunnerOutput/OutputHandlers.expect.consoleLines.txt, tests/RunnerOutput/OutputHandlers.phpt
Usage example:
```sh
$ ./src/tester -C -o console-lines tests/
```
This is handy for environments with "non-standard" _(buffered, I guess?)_ handling of standard output, for example `Github Actions` _(where a progress of tests cannot be seen until until end-of-line appears, which in standard `console` mode happens only when all tests finish)_ or `Docker Compose` logging output _(where in standard `console` mode each finished test's dot is printed alone on separate line)_.
Or the `console-lines` mode can be handy just to see a more detailed progress of tests in all environments, because it outputs something like this:
<table>
<tr>
<td>Passing tests</td>
<td>Failing tests</td>
<td>Usage</td>
<td>Also supports "cider mode"</td>
<tr/>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<tr/> …
=> Added `console-lines` output mode which prints each test on a separate line

src/Framework/Helpers.php, src/Runner/Test.php, src/Runner/TestHandler.php, tests/Runner/Job.phpt
Resolves https://github.com/nette/tester/issues/448.
- new feature
- BC break? no (hopefully)
For tests wrapped in testcase class:
```php
class MyTests extends \Tester\Testcase {
public function testMethod_1() { ... }
public function testMethod_2() { ... }
}
```
... where Tester creates a separate `Test` object for each of the testcase's methods, ***we now add (append) the method's name to the (maybe already specified) test's title***.
In the case of these two methods, if this PR is merged, the first test object will now have the title `"testMethod_1"` and the second one will have the title `"testMethod_2"`.
... if Nette Tester self-tests with [`-o console-lines` output mode](https://github.com/nette/tester/pull/443):
Yes, the test file might also contain "a primary, standalone title …
=> Add testcase method's name to the test's title

src/Runner/TestHandler.php
Use full length of MD5 to make collisions more difficult
- bug fix / new feature?   Bugfix
- BC break? no
- doc PR: just fixed issue
This PR fixed rare situation, when first 5 characters in MD5 of file was same, so Nette/Tester could not run tests properly.
=> Fix: first 5 characters is too weak for collisions

.github/workflows/tests.yml, composer.json, src/CodeCoverage/Generators/AbstractGenerator.php
paving the way to support PHP 8.5 so other dev-tooling which depend on nette/* packages can start supporting 8.5 as well
=> Declare PHP 8.5 support
